// Contract test — client `classifyFit()` MUST agree with the BE classifier.
//
// Backend authority: `app/models/fit.py:classify_fit` (locked constants
// GREEN_RATIO=0.55, YELLOW_RATIO=0.80, ORANGE_RATIO=1.0; budget<=0 → "red").
// Frontend mirror: `src/lib/fit.ts:classifyFit`.
//
// We can't drive the live `POST /api/models/fit-preview` from vitest (no
// FastAPI in this test runner), so we lock the contract three ways instead:
//
//   1. Exported thresholds are numerically equal to the BE values. If a BE
//      change bumps GREEN_RATIO and the FE constant drifts, this fails.
//   2. A frozen table of representative (file_size, budget, server_verdict)
//      tuples — these were generated by feeding plausible inputs through
//      `app/models/fit.classify_fit` on the matching commit. Each row asserts
//      `classifyFit(file_size, budget) === server_verdict`.
//   3. Boundary-condition spot checks: budget<=0 → "red", and the ratio
//      ladder lands on the correct band at, just below, and just above each
//      published threshold.
//
// When the BE classifier intentionally changes thresholds, update the
// constants in `src/lib/fit.ts` AND regenerate the fixture rows here in
// lockstep. This test is the loud canary that catches silent drift.

import { describe, it, expect } from "vitest";
import {
  classifyFit,
  GREEN_RATIO,
  YELLOW_RATIO,
  ORANGE_RATIO,
  RATIO_OVERFLOW_SENTINEL,
  RECOMMENDATION_TARGET_RATIO,
  recommendMaxModelLen,
} from "@/lib/fit";

const GIB = 1024 * 1024 * 1024;

describe("classifyFit — locked thresholds match BE `app/models/fit.py`", () => {
  it("exports GREEN_RATIO=0.55 / YELLOW_RATIO=0.80 / ORANGE_RATIO=1.0", () => {
    expect(GREEN_RATIO).toBe(0.55);
    expect(YELLOW_RATIO).toBe(0.80);
    expect(ORANGE_RATIO).toBe(1.0);
  });

  it("exports RATIO_OVERFLOW_SENTINEL=1e9 (matches FitPreviewResponse JSON sentinel)", () => {
    expect(RATIO_OVERFLOW_SENTINEL).toBe(1e9);
  });
});

describe("classifyFit — verdict ladder", () => {
  it("returns 'red' immediately for budget <= 0 (KV alone overflows VRAM)", () => {
    // Both branches the BE takes — budget == 0 and budget < 0 (the KV
    // reserve was larger than the capped VRAM allotment).
    expect(classifyFit(1 * GIB, 0)).toBe("red");
    expect(classifyFit(1 * GIB, -1)).toBe("red");
    expect(classifyFit(1 * GIB, -100 * GIB)).toBe("red");
  });

  // Representative rows. Each tuple is `[file_size, budget, verdict]`,
  // chosen so the resulting ratio sits firmly inside one band — not on
  // a boundary. Generated by mirroring inputs through BE
  // `classify_fit(file_size, budget)` on the matching commit.
  const ROWS: ReadonlyArray<[number, number, "green" | "yellow" | "orange" | "red"]> = [
    // green band: ratio < 0.55
    [4 * GIB, 20 * GIB, "green"],   // 0.20
    [8 * GIB, 20 * GIB, "green"],   // 0.40
    [10 * GIB, 20 * GIB, "green"],  // 0.50
    // yellow band: 0.55 <= ratio < 0.80
    [11 * GIB, 20 * GIB, "yellow"], // 0.55
    [12 * GIB, 20 * GIB, "yellow"], // 0.60
    [14 * GIB, 20 * GIB, "yellow"], // 0.70
    // orange band: 0.80 <= ratio < 1.0
    [16 * GIB, 20 * GIB, "orange"], // 0.80
    [18 * GIB, 20 * GIB, "orange"], // 0.90
    [19 * GIB, 20 * GIB, "orange"], // 0.95
    // red band: ratio >= 1.0
    [20 * GIB, 20 * GIB, "red"],    // 1.00
    [24 * GIB, 20 * GIB, "red"],    // 1.20
    [40 * GIB, 20 * GIB, "red"],    // 2.00
  ];

  it.each(ROWS)(
    "file_size=%d budget=%d → %s",
    (fileSize, budget, expected) => {
      expect(classifyFit(fileSize, budget)).toBe(expected);
    },
  );
});

describe("classifyFit — boundary conditions", () => {
  // Float math at boundary points: the BE uses strict `<` comparisons so
  // the threshold itself falls into the *higher* tier. Mirror that exactly.
  it("ratio just below 0.55 → green", () => {
    // 0.549 = green; pick numbers that arithmetic in JS lands exactly.
    expect(classifyFit(549, 1000)).toBe("green");
  });

  it("ratio exactly 0.55 → yellow (boundary is exclusive on the lower side)", () => {
    expect(classifyFit(550, 1000)).toBe("yellow");
  });

  it("ratio just below 0.80 → yellow", () => {
    expect(classifyFit(799, 1000)).toBe("yellow");
  });

  it("ratio exactly 0.80 → orange", () => {
    expect(classifyFit(800, 1000)).toBe("orange");
  });

  it("ratio just below 1.0 → orange", () => {
    expect(classifyFit(999, 1000)).toBe("orange");
  });

  it("ratio exactly 1.0 → red", () => {
    expect(classifyFit(1000, 1000)).toBe("red");
  });

  it("RATIO_OVERFLOW_SENTINEL signals 'red' indirectly via budget<=0 path", () => {
    // The sentinel itself is only present in the BE response payload —
    // the FE doesn't pass it to `classifyFit()`. The flow is: server
    // produces `ratio=1e9` and `verdict="red"` when budget<=0, the FE
    // renders the server verdict on first paint, then any client
    // reclassify also lands on "red" because liveBudget collapses to
    // a non-positive value through the same math path. We just sanity
    // check that the sentinel is large enough to be classified red if
    // it ever leaked into the classifier as a literal ratio.
    expect(classifyFit(RATIO_OVERFLOW_SENTINEL * 1000, 1000)).toBe("red");
  });
});

// ---------------------------------------------------------------------------
// recommendMaxModelLen — direct unit coverage for the client-side fallback
// solver. The BE counterpart at `app/models/fit.py:recommend_max_model_len`
// is the authority; this suite locks the FE implementation against the same
// formula and every null-return branch.
//
// Why test directly (vs only the modal): when the backend's
// `recommended_max_model_len` field is absent on an orange row, the modal
// falls back to this helper to populate the "Recommended L" hint. A silent
// regression here (off-by-one, wrong floor, missed null branch) shows up as
// an empty hint or a garbage value pasted into the override input — both of
// which the user sees but the modal-level test wouldn't catch precisely.
// ---------------------------------------------------------------------------
describe("recommendMaxModelLen — fallback solver matches BE formula", () => {
  it("exports RECOMMENDATION_TARGET_RATIO=0.70 (matches BE app/models/fit.py)", () => {
    expect(RECOMMENDATION_TARGET_RATIO).toBe(0.70);
  });

  it("happy path — solves the same formula as the backend", () => {
    // Mirror the BE math exactly (`app/models/routes_api.py:439-457`):
    //
    //   needed_weights = file_size / target
    //   numerator      = cap - needed_weights
    //   L              = floor(numerator / bytes_per_token)
    //
    // Pick numbers that produce a clean integer result so float drift
    // can't muddy the assertion.
    //
    //   fileSize        = 14 GiB              (14 * 2^30)
    //   capBytes        = 20 GiB              (20 * 2^30)
    //   bytesPerToken   = 1 MiB               (2^20) — large value to keep L small
    //   targetRatio     = 0.70 (default)
    //   neededWeights   = 14 GiB / 0.70 = 20 GiB
    //   numerator       = 20 GiB - 20 GiB = 0
    //
    // That'd return null, so bump capBytes to 21 GiB → numerator = 1 GiB:
    //   L = floor(1 GiB / 1 MiB) = 1024.
    const GIB = 1024 * 1024 * 1024;
    const MIB = 1024 * 1024;
    const L = recommendMaxModelLen({
      fileSize: 14 * GIB,
      capBytes: 21 * GIB,
      bytesPerToken: MIB,
    });
    expect(L).toBe(1024);
  });

  it("happy path — accepts custom targetRatio that lowers L", () => {
    // Same inputs as above but target tightened to 0.55 (green band).
    //   neededWeights = 14 GiB / 0.55 ≈ 25.45 GiB > capBytes (21 GiB)
    //   → returns null (no headroom for KV at any L).
    const GIB = 1024 * 1024 * 1024;
    const MIB = 1024 * 1024;
    const L = recommendMaxModelLen({
      fileSize: 14 * GIB,
      capBytes: 21 * GIB,
      bytesPerToken: MIB,
      targetRatio: 0.55,
    });
    expect(L).toBeNull();
  });

  it("bytesPerToken === 0 → null (division-by-zero guard)", () => {
    // KV cost per token is 0 only when num_kv_heads or num_layers is 0,
    // which means we can't form a meaningful budget recommendation.
    expect(
      recommendMaxModelLen({
        fileSize: 10 * 1024 * 1024 * 1024,
        capBytes: 20 * 1024 * 1024 * 1024,
        bytesPerToken: 0,
      }),
    ).toBeNull();
  });

  it("bytesPerToken < 0 → null (caller passed garbage)", () => {
    // Defensive guard: BE uses `<= 0` to short-circuit; mirror that.
    expect(
      recommendMaxModelLen({
        fileSize: 10 * 1024 * 1024 * 1024,
        capBytes: 20 * 1024 * 1024 * 1024,
        bytesPerToken: -1,
      }),
    ).toBeNull();
  });

  it("targetRatio === 0 → null (would divide by zero on neededWeights)", () => {
    expect(
      recommendMaxModelLen({
        fileSize: 1024,
        capBytes: 2048,
        bytesPerToken: 1,
        targetRatio: 0,
      }),
    ).toBeNull();
  });

  it("targetRatio < 0 → null", () => {
    expect(
      recommendMaxModelLen({
        fileSize: 1024,
        capBytes: 2048,
        bytesPerToken: 1,
        targetRatio: -0.5,
      }),
    ).toBeNull();
  });

  it("neededWeights >= capBytes → null (no headroom for KV at any L)", () => {
    // fileSize / target == capBytes exactly → numerator = 0 → null.
    // The model can't fit at the target ratio with any context length.
    expect(
      recommendMaxModelLen({
        fileSize: 700, // 700 / 0.70 = 1000 == capBytes
        capBytes: 1000,
        bytesPerToken: 1,
      }),
    ).toBeNull();
    // And the strictly-greater case (model larger than VRAM after target):
    expect(
      recommendMaxModelLen({
        fileSize: 800,
        capBytes: 1000,
        bytesPerToken: 1,
      }),
    ).toBeNull();
  });

  it("computed L < 1 → null (don't paste 0 into the override input)", () => {
    // numerator just barely positive, bytesPerToken huge → L = 0.
    //   fileSize=70, target=0.70 → neededWeights=100
    //   capBytes=101 → numerator=1
    //   bytesPerToken=2 → 1/2 = 0.5 → floor = 0 → null
    //
    // vLLM rejects max_model_len < 1, so the FE must NOT surface 0.
    expect(
      recommendMaxModelLen({
        fileSize: 70,
        capBytes: 101,
        bytesPerToken: 2,
      }),
    ).toBeNull();
  });

  it("computed L === 1 → 1 (lowest valid context — still surface it)", () => {
    // numerator exactly equals bytesPerToken → L = 1 (vLLM accepts).
    //   fileSize=70, target=0.70 → neededWeights=100
    //   capBytes=102 → numerator=2
    //   bytesPerToken=2 → L = 1
    expect(
      recommendMaxModelLen({
        fileSize: 70,
        capBytes: 102,
        bytesPerToken: 2,
      }),
    ).toBe(1);
  });

  it("floors fractional L (mirrors BE int(numerator // kv_per_token))", () => {
    // numerator=10, bytesPerToken=3 → 3.33 → floor = 3.
    //   fileSize=70, target=0.70 → neededWeights=100
    //   capBytes=110 → numerator=10
    expect(
      recommendMaxModelLen({
        fileSize: 70,
        capBytes: 110,
        bytesPerToken: 3,
      }),
    ).toBe(3);
  });
});
