"""The live-stats frame, frozen before the metric dialect moves.

Sub-project C splits app/stats/live_engine.py's 31 hard-coded ``vllm:`` metric
names out of build_frame() so a second backend can supply its own. The frame
that comes out the other side is the dashboard's contract -- eleven panels in
frontend/src/app/stats/live/page.tsx read it field by field -- so the split has
to be provably shape-preserving, not argued to be.

Two cases, because build_frame has two modes: prev=None (the first frame after a
connection opens, where every rate is null) and prev=<snapshot> (the steady
state, where the rate math and the counter-reset guard run). A refactor that
broke only the second would otherwise pass.

The golden file is generated by the __main__ block at the bottom of this module
and committed. Regenerating it is a deliberate act with a visible diff.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.runtime.backends.vllm import VllmBackend
from app.stats.live_engine import RateState, build_frame

_HERE = Path(__file__).resolve().parent
_REPO = _HERE.parents[2]
METRICS_TXT = _HERE / "fixtures" / "vllm_metrics_0_25_1.txt"
GOLDEN = _REPO / "tests" / "fixtures" / "live_frame_golden.json"

# A previous-tick snapshot 10 simulated seconds behind the fixture's counters.
# The numbers are chosen so every rate is a clean, human-checkable value:
# generation 500000 - 400000 = 100000 over 10s = 10000 tok/s, and so on. A
# reviewer can verify the golden by arithmetic instead of by trusting the
# generator that wrote it.
PREV = RateState(
    monotonic=1000.0,
    gen=400000.0,
    prompt=900000.0,
    preempt=2.0,
    prefix_hits=50000.0,
    prefix_queries=100000.0,
)
NOW = 1010.0


def _frames() -> dict:
    reading = VllmBackend().parse_metrics(METRICS_TXT.read_text())
    first, _ = build_frame(
        reading,
        model="m",
        model_id="mid",
        max_model_len=4096,
        prev=None,
        scrape_monotonic=NOW,
    )
    rated, _ = build_frame(
        reading,
        model="m",
        model_id="mid",
        max_model_len=4096,
        prev=PREV,
        scrape_monotonic=NOW,
    )
    # ``ts`` is wall-clock; it is the one field that cannot be frozen.
    for f in (first, rated):
        f.pop("ts")
        # Added by Task 4; asserted separately below so the golden written
        # before the split stays byte-for-byte valid after it.
        f.pop("backend")
    return {"first_frame": first, "rate_frame": rated}


def test_frame_carries_the_backend_name():
    reading = VllmBackend().parse_metrics(METRICS_TXT.read_text())
    frame, _ = build_frame(
        reading,
        model="m",
        model_id="mid",
        max_model_len=None,
        prev=None,
        scrape_monotonic=NOW,
    )
    assert frame["backend"] == "vllm"


@pytest.mark.parametrize("case", ["first_frame", "rate_frame"])
def test_frame_matches_golden(case):
    golden = json.loads(GOLDEN.read_text())
    assert _frames()[case] == golden[case]


def test_first_frame_has_null_rates():
    """Pinned separately from the golden because it is the INVARIANT, not the
    value: a connection's first tick has no previous counter to subtract, and a
    dashboard that showed 0 tok/s there would be lying about an idle engine."""
    f = _frames()["first_frame"]
    assert f["throughput"]["generation_tokens_per_s"] is None
    assert f["throughput"]["prompt_tokens_per_s"] is None
    assert f["engine"]["preemptions_per_s"] is None
    assert f["cache"]["prefix_hit_rate"] is None


def test_rate_frame_rates_are_arithmetic():
    f = _frames()["rate_frame"]
    assert f["throughput"]["generation_tokens_per_s"] == pytest.approx(10000.0)
    assert f["throughput"]["prompt_tokens_per_s"] == pytest.approx(10000.0)
    assert f["engine"]["preemptions_per_s"] == pytest.approx(1.0)


def test_absent_metric_is_null_not_zero():
    """The property the whole llama.cpp dialect rests on. The fixture publishes
    no vllm:mm_cache_hits_total / vllm:external_prefix_cache_hits_total series,
    and the frame must say so with null rather than 0 -- design spec §9.1
    and §9.3.

    (The plan named vllm:estimated_flops_per_gpu_total here; that series IS in
    the fixture, at 1.2e15, so it proves the opposite of the point. The two
    cache ratios are the genuinely-absent ones.)
    """
    f = _frames()["first_frame"]
    assert f["cache"]["mm_hit_rate_cumulative"] is None
    assert f["cache"]["external_prefix_hit_rate_cumulative"] is None


if __name__ == "__main__":  # pragma: no cover -- generator, run by hand
    GOLDEN.parent.mkdir(parents=True, exist_ok=True)
    GOLDEN.write_text(json.dumps(_frames(), indent=2, sort_keys=True) + "\n")
    print(f"wrote {GOLDEN}")
